import React, { useState } from "react";

const AIQuizPreview = ({ aiQuizData, onAccept, onRegenerate, onCancel }) => {
  const [editingQuestionIndex, setEditingQuestionIndex] = useState(-1);
  const [editedQuestions, setEditedQuestions] = useState(aiQuizData.questions);
  const [quizTitle, setQuizTitle] = useState(aiQuizData.title);
  const [quizDescription, setQuizDescription] = useState(
    aiQuizData.description || ""
  );

  const handleQuestionEdit = (index, field, value) => {
    const updated = [...editedQuestions];
    updated[index] = { ...updated[index], [field]: value };
    setEditedQuestions(updated);
  };

  const handleChoiceEdit = (questionIndex, choiceIndex, value) => {
    const updated = [...editedQuestions];
    updated[questionIndex].choices[choiceIndex] = value;
    setEditedQuestions(updated);
  };

  const handleCorrectAnswerChange = (questionIndex, choiceIndex) => {
    const updated = [...editedQuestions];
    updated[questionIndex].correctAnswer =
      updated[questionIndex].choices[choiceIndex];
    setEditedQuestions(updated);
  };

  const handleAccept = () => {
    const finalQuizData = {
      ...aiQuizData,
      title: quizTitle,
      description: quizDescription,
      questions: editedQuestions,
    };
    onAccept(finalQuizData);
  };

  const deleteQuestion = (index) => {
    const updated = editedQuestions.filter((_, i) => i !== index);
    setEditedQuestions(updated);
    setEditingQuestionIndex(-1);
  };

  const addNewQuestion = () => {
    const newQuestion = {
      content: "New question",
      type: "multiple-choice",
      choices: ["Option A", "Option B", "Option C", "Option D"],
      correctAnswer: "Option A",
      points: 1,
      explanation: "",
    };
    setEditedQuestions([...editedQuestions, newQuestion]);
  };

  return (
    <div className="max-w-6xl mx-auto bg-white/5 p-6 rounded-lg shadow-md">
      <div className="flex justify-between items-start mb-6">
        <div className="flex-1 mr-6">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-2xl">🤖</span>
            <h2 className="text-2xl font-semibold">
              AI Generated Quiz Preview
            </h2>
          </div>
          <div className="bg-green-900/30 border border-green-600 p-3 rounded-lg">
            <p className="text-green-200 text-sm">
              ✨ AI generated {editedQuestions.length} questions • Difficulty:{" "}
              <span className="font-medium capitalize">
                {aiQuizData.difficulty}
              </span>{" "}
              • Generated by: {aiQuizData.generatedBy}
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <button
            onClick={onRegenerate}
            className="px-4 py-2 rounded bg-purple-600 hover:bg-purple-700 text-sm"
          >
            🔄 Regenerate
          </button>
          <button
            onClick={onCancel}
            className="px-4 py-2 rounded bg-gray-600 hover:bg-gray-700 text-sm"
          >
            Cancel
          </button>
        </div>
      </div>

      {/* Quiz Title and Description */}
      <div className="bg-slate-800/50 p-4 rounded-lg mb-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Quiz Title *
            </label>
            <input
              type="text"
              value={quizTitle}
              onChange={(e) => setQuizTitle(e.target.value)}
              className="w-full p-3 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Description (Optional)
            </label>
            <input
              type="text"
              value={quizDescription}
              onChange={(e) => setQuizDescription(e.target.value)}
              className="w-full p-3 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
            />
          </div>
        </div>
      </div>

      {/* Original Prompt Info */}
      <div className="bg-blue-900/30 border border-blue-600 p-3 rounded-lg mb-6">
        <p className="text-blue-200 text-sm">
          <span className="font-medium">Original Prompt:</span> "
          {aiQuizData.prompt}"
        </p>
      </div>

      {/* Questions List */}
      <div className="space-y-4 mb-6">
        <div className="flex justify-between items-center">
          <h3 className="text-lg font-medium">
            Questions ({editedQuestions.length})
          </h3>
          <button
            onClick={addNewQuestion}
            className="px-3 py-1 text-sm bg-indigo-600 hover:bg-indigo-700 rounded"
          >
            + Add Question
          </button>
        </div>

        {editedQuestions.map((question, index) => (
          <div
            key={index}
            className="bg-slate-800/50 border border-slate-700 rounded-lg p-4"
          >
            <div className="flex justify-between items-start mb-3">
              <span className="text-sm text-gray-400">
                Question {index + 1}
              </span>
              <div className="flex gap-2">
                <button
                  onClick={() =>
                    setEditingQuestionIndex(
                      editingQuestionIndex === index ? -1 : index
                    )
                  }
                  className="text-xs px-2 py-1 bg-indigo-600 hover:bg-indigo-700 rounded"
                >
                  {editingQuestionIndex === index ? "Done" : "Edit"}
                </button>
                <button
                  onClick={() => deleteQuestion(index)}
                  className="text-xs px-2 py-1 bg-red-600 hover:bg-red-700 rounded"
                >
                  Delete
                </button>
              </div>
            </div>

            {editingQuestionIndex === index ? (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Question Content
                  </label>
                  <textarea
                    value={question.content}
                    onChange={(e) =>
                      handleQuestionEdit(index, "content", e.target.value)
                    }
                    className="w-full p-2 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
                    rows="2"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Answer Choices
                  </label>
                  <div className="space-y-2">
                    {question.choices.map((choice, choiceIndex) => (
                      <div
                        key={choiceIndex}
                        className="flex items-center gap-3"
                      >
                        <input
                          type="radio"
                          name={`correct-${index}`}
                          checked={question.correctAnswer === choice}
                          onChange={() =>
                            handleCorrectAnswerChange(index, choiceIndex)
                          }
                          className="w-4 h-4"
                        />
                        <input
                          type="text"
                          value={choice}
                          onChange={(e) =>
                            handleChoiceEdit(index, choiceIndex, e.target.value)
                          }
                          className="flex-1 p-2 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
                          placeholder={`Option ${String.fromCharCode(
                            65 + choiceIndex
                          )}`}
                        />
                      </div>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Points
                    </label>
                    <input
                      type="number"
                      min="1"
                      max="10"
                      value={question.points}
                      onChange={(e) =>
                        handleQuestionEdit(
                          index,
                          "points",
                          parseInt(e.target.value) || 1
                        )
                      }
                      className="w-full p-2 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Explanation (Optional)
                    </label>
                    <input
                      type="text"
                      value={question.explanation || ""}
                      onChange={(e) =>
                        handleQuestionEdit(index, "explanation", e.target.value)
                      }
                      className="w-full p-2 rounded bg-slate-700 text-white border border-slate-600 focus:border-indigo-500 focus:outline-none"
                      placeholder="Why this answer is correct..."
                    />
                  </div>
                </div>
              </div>
            ) : (
              <div>
                <h4 className="font-medium text-white mb-3">
                  {question.content}
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-3">
                  {question.choices.map((choice, choiceIndex) => (
                    <div
                      key={choiceIndex}
                      className={`p-2 rounded border text-sm ${
                        choice === question.correctAnswer
                          ? "bg-green-900/30 border-green-600 text-green-200"
                          : "bg-slate-700 border-slate-600 text-gray-300"
                      }`}
                    >
                      <span className="font-medium">
                        {String.fromCharCode(65 + choiceIndex)}.
                      </span>{" "}
                      {choice}
                      {choice === question.correctAnswer && (
                        <span className="ml-2 text-green-400">✓ Correct</span>
                      )}
                    </div>
                  ))}
                </div>
                <div className="flex justify-between text-sm text-gray-400">
                  <span>Points: {question.points}</span>
                  {question.explanation && (
                    <span>💡 {question.explanation}</span>
                  )}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Action Buttons */}
      <div className="flex justify-center gap-4 pt-4 border-t border-slate-700">
        <button
          onClick={handleAccept}
          disabled={!quizTitle.trim() || editedQuestions.length === 0}
          className="px-8 py-3 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
        >
          ✨ Create Quiz ({editedQuestions.length} questions)
        </button>
      </div>
    </div>
  );
};

export default AIQuizPreview;
